[package]
name = "jjump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0"
serde = "1"

[dependencies.clap]
version = "4"
features = ["derive"]
